name: Build release package
on:
  push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build Code
        run: |
          git clone https://github.com/mqk233/Lenovo-Y9000X-Hackintosh && cd Lenovo-Y9000X-Hackintosh && chmod +x **/*.sh && ./build.sh
          zip --junk-paths Lenovo-Y9000X-Hackintosh.zip ./Output/*
      - name: Create Release
        id: create-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./Lenovo-Y9000X-Hackintosh.zip
          asset_name: Lenovo-Y9000X-Hackintosh.zip
          asset_content_type: application/zip
